### ISSUE TITLE
Swarmer got stuck on "Starting emulator" if it started on a remote machine via SSH

### ISSUE THREAD

**Issue by Adambl4** [gojuno/swarmer#27]
```console
ssh remote-machine
java -jar swarmer.jar start ...
```
Output:
```
[Fri Jul 21 16:01:59 MSK 2017]: Already running emulators: []
[Fri Jul 21 16:01:59 MSK 2017]: Creating avd test_emulator_1.
[Fri Jul 21 16:02:01 MSK 2017]: Avd test_emulator_1 created in 2.346 seconds.
[Fri Jul 21 16:02:01 MSK 2017]: Ports for emulator test_emulator_1: 5554, 5555.
[Fri Jul 21 16:02:01 MSK 2017]: Starting emulator test_emulator_1.
Timeout 180 seconds, failed to start emulator test_emulator_1.
```

The same command works well if it executed on the remote-machine directly.

**Comment by artem-zinnatullin** [comment]
Hm, probably when you do it with `ssh` you're dropping some important variables, Swarmer needs `$ANDROID_HOME`, can you check if its available when you do non-interactive ssh session?

```console
ssh remote-machine echo $ANDROID_HOME
```

This should output path to Android SDK on remote machine.

**Comment by Adambl4** [comment]
Yes, it's available for non-interactive session.
Swarmer able to create an avd, so it found $ANDROID_HOME actually.

**Comment by artem-zinnatullin** [comment]
Okay, to diagnose problem I would recommend to run `ssh remote_machine tail -f *.output` in parallel to `ssh remote_machine java -jar swarmer.jar`. 

Swarmer interacts with external tools like Android SDK by writing their output to temporary files so you can see if some of the external tool did print something suspicious.

Also, you might be trying to launch emulator with window but non-interactive ssh session may not have `DISPLAY` env variable, can you please check it? `ssh remote_machine echo \$DISPLAY` (please note `\`) it should display something like `:0`.

**Comment by Adambl4** [comment]
Missing `$DISPLAY` was the reason.

**Comment by artem-zinnatullin** [comment]
Great! 

Yeah, this is how you provide access to window server on Linux distros.
