### ISSUE TITLE
/tools/emulator is deprecated, consider using /emulators/emulator

### ISSUE THREAD

**Issue by soundcloudfrank** [gojuno/swarmer#31]
The emulator in android-studio/tools is deprecated. Consider migrating to android-studio/emulator/emulator, which allows for redirection depending on architecture, and is actively supported.

**Comment by artem-zinnatullin** [comment]
Hmm, can you find documentation page that says that?

https://developer.android.com/studio/run/emulator-commandline.html suggests to use `tools/emulator` which we use right now.

**Comment by soundcloudfrank** [comment]
I misspoke. It's not deprecated, per se, but it creates issues when running on 64 bit machines. E.g. https://askubuntu.com/questions/534044/error-32-bit-linux-android-emulator-binaries-are-deprecated-when-attemping-to-r

**Comment by artem-zinnatullin** [comment]
No, it doesn't :) 

The issue you've linked is about running emulators on 32-bit Linux distro and recommended fix is to run emulators on 64-bit Linux distros.

No action required for us.

**Comment by soundcloudfrank** [comment]
I AM running on a 64 bit distro. Ah well.

**Comment by artem-zinnatullin** [comment]
Where do you see this error?

**Comment by ming13** [comment]
I don’t have a documented statement, that `tools/emulator` is deprecated, but only [a comment](https://issuetracker.google.com/issues/63064805#comment4) that `platform-26` works only with `emulator/emulator`.

Things are strange about them.

```
[~] → $ANDROID_HOME/tools/emulator -version
Android emulator version 26.1.4.0 (build_id 4266726) (CL:add3139bafe4f34502c851716afcee834068103a)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

[~] → $ANDROID_HOME/emulator/emulator -version
Android emulator version 26.1.4.0 (build_id 4266726) (CL:add3139bafe4f34502c851716afcee834068103a)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
```
And yet.
```
[~] → $ANDROID_HOME/emulator/emulator -avd Nexus-4 -verbose -show-kernel
emulator:Android emulator version 26.1.4.0 (build_id 4266726) (CL:add3139bafe4f34502c851716afcee834068103a)

[~] → $ANDROID_HOME/tools/emulator -avd Nexus-4 -verbose -show-kernel
emulator:Android emulator version 25.3.0.0 (build_id 3394391)
```
In other words, seems like `tools/emulator` is the old one and `emulator/emulator` is the new one. 

And I can confirm that `tools` one did not work for us with `26` and newer `25` revisions, but `emulator` one did the trick — not completely, but at least it started and passed the suite a couple of times.

**Comment by artem-zinnatullin** [comment]
Tanks for update, would be great to confirm this with Android Developer Tools team though.

**Comment by ming13** [comment]
> Tanks for update, would be great to confirm this with Android Developer Tools team though.

Yes, this kind of _tanks_.

Just opened the issue regarding this — https://issuetracker.google.com/issues/66886035

**Comment by ming13** [comment]
Seems like we have our answer — `emulator/emulator` is a way to go.
