### ISSUE TITLE
Option to keep existing AVDs

### ISSUE THREAD

**Issue by simonschiller** [gojuno/swarmer#41]
Currently, AVDs get deleted and recreated on every execution of swarmer. To speed up our tests we would like to keep existing AVDs. A flag to keep AVDs if they already exist would be great, something like `--keep-existing-avds`.

**Comment by artem-zinnatullin** [comment]
Originally Swarmer was intentionally made stateless to avoid corrupted state reuse on CI, but then we moved it even deeper and started to run emulators in Docker container so it was stateless even more.

I understand that it's not the way others use it normally, so I guess it's fine to adopt it…
